[window]

opacity = 0.85

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light"

[scrolling]
history = 10000
multiplier = 4

[font]

normal.family = "Cascadia Code PL"
bold.family = "Cascadia Code PL"
italic.family = "Cascadia Code PL"
bold_italic.family = "Cascadia Code PL"

size = 12.0

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
