"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$character"""

#$git_status\

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-green bold"

[git_status]
format = '[$all_status]($style) '
style = "bold red"
conflicted = "!"
up_to_date = ""
untracked = "?"
ahead = "↑"
diverged = "↕"
behind = "↓"
stashed = "$"
modified = "M"
staged = "+"
renamed = "R"
deleted = "D"

[directory]
truncation_length = 5
truncation_symbol = ""
home_symbol = "~"
format = "[$path]($style) "
style = "bold cyan"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[username]
style_user = "whitteee"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "whitteee"
disabled = false
